version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
    extra_hosts:
      - "host.docker.internal:host-gateway"
    
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=vitalvibes
      - MYSQL_DATABASE=vitalvibes
      - MYSQL_USER=vitalvibes
      - MYSQL_PASSWORD=vitalvibes
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: 